version: '3.9'
services:
  strapi:
    image: strapi/strapi
    container_name: strapi_container
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'
    links: 
      - postgres
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: database_container
    ports: 
      - 5432:5432 
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - ./data:/var/lib/postgresql/data